### ISSUE TITLE
Tlist_Exit_OnlyWindow doesn't work on a tabpage

### ISSUE THREAD

**Issue by walterchenqq** [yegappan/taglist#15]
vim 9.1, linux 3.10, Tlist_Exit_OnlyWindow is set to 1

open a source file A
tabnew another source file B with taglist window open
close B by "quit" command
error occurs and taglist window is not closed // you have to close it by another 'quit'
error message shows as below:
Error detected while processing BufEnter Autocommands for "__Tag_List__"..function <SNR>47_Tlist_Window_Exit_Only_Window:
line   14:
E1312: Not allowed to change the window layout in this autocmd

**Comment by yegappan** [comment]
Thanks for reporting the issue.  This is fixed by ada73c5987e2988a57d63a3e0b9beb6fd0980349.
