### ISSUE TITLE
autocmd Cursorhold calls missing function

### ISSUE THREAD

**Issue by Hans-Guenter** [yegappan/taglist#7]
The autocmd Cursorhold command at line 1188 in autoload/taglist.vimm at line 1188 calls a missing function.
The correct function name seems to lack a leading "s:". (i.e. call s:Tlist_Window_Show_Info())

A related issue is that
function! **s:Tlist_Ballon_Expr**
needs to be renamed
function! **taglist#Tlist_Ballon_Expr**
because it's used in the balloonexpr and thus not evaluated in a script context.

**Comment by yegappan** [comment]
Thanks for reporting these issues.  I have pushed fixes for these.
