### ISSUE TITLE
E117: Unknown function: taglist#Tlist_Window_Check_Auto_Open

### ISSUE THREAD

**Issue by tr4v3ler** [yegappan/taglist#8]
In my ~/.vimrc, Tlist_Auto_Open is enabled. When I start vim in a folder, I met this error:
```
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: taglist#Tlist_Window_Check_Auto_Open
```

**Comment by yegappan** [comment]
I have committed 293152b252ee9f972c430e47e6a2281373c3afce to fix this issue.

**Comment by tr4v3ler** [comment]
Thank you for your reply. 
The bug has indeed been fixed, but when I start vim in a directory, the taglist window does not pop up. I expect a blank window to pop up, and taglist will update automatically when I later open a file.

**Comment by tr4v3ler** [comment]
> I have committed [293152b](https://github.com/yegappan/taglist/commit/293152b252ee9f972c430e47e6a2281373c3afce) to fix this issue.

Thank you for your reply. 
The bug has indeed been fixed, but when I start vim in a directory, the taglist window does not pop up. I expect a blank window to pop up, and taglist will update automatically when I later open a file.

**Comment by yegappan** [comment]
The taglist window is automatically opened only when you supply a filename to Vim.  If the file is not one of the supported types (e.g. a plain text file) or is a directory, then the taglist window is not opened.  This is to avoid opening the taglist window when editing a temporary file (e.g. a Git commit message).
